name: Deploy static website to gh-pages branch

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Git
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        giti remote add github_origin https://EPLStudents:${{secrets.CI_HOKKAYDO_ACCESS_TOKEN}}@github.com/eplstudents.github.io
      
    - name: Run gen_static.sh script
      run: sh gen_static.sh

    - name: Push to gh-pages branch
      run: |
        git add -f static/
        git commit -m "Update static content"
        git push github_origin $(git subtree split --prefix static master):gh-pages -f
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
