name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: ci-${{ github.ref }}
    steps:
      - uses: actions/checkout@v4.1.7 # This action checks out your repository
      - name: Run gen_static.sh script
        run: sh gen_static.sh
      - name: Build and Deploy
        uses: JamesIves/github-pages-deploy-action@v4.6.8
        with:
          branch: gh-pages
          folder: static
          clean: true